### ISSUE TITLE
Doesn't work with the latest meteor

### ISSUE THREAD

**Issue by andreyantipov** [jagi/meteor-fabricjs#2]
Meteor 1.1.0.3

While checking for jagi:node-canvas@0.1.0:
error: No compatible binary build found for this package. Contact the package author and ask them to
publish it for your platform.

**Comment by lukejagodzinski** [comment]
Hi, the problem is that I haven't published binaries at all for any platform. When I was creating this package I didn't know that I have to. You can solve this by installing node-canvas for your operating system by yourself.

Right now I don't have time to deal with it because I'm busy with development of the Astronomy package

**Comment by andreyantipov** [comment]
Got it.

Btw. astronomy is awesome!
